/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\Petra.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Petra(props) {
  const { nodes, materials } = useGLTF('models/Petra.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} rotation={[0,0, 0]}>
      {/* <meshStandardMaterial attach="material" color={"#6be092"} /> */}
      <pointLight position={[0,250,14]} intensity={8} color="yellow" />
      </mesh>
    </group>
  )
}

useGLTF.preload('models/Petra.glb')
