/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\Christ the Redeemer.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Redeemer(props) {
  const { nodes, materials } = useGLTF('models/Christ the Redeemer.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} rotation={[-Math.PI / 2, 0, -Math.PI/2]} />
      <pointLight position={[0, 250, 14]} intensity={8} color="yellow" />
    </group>
  )
}

useGLTF.preload('models/Christ the Redeemer.glb')
